id: 21
os: iosxr
ansible_password: cisco123
napalm_driver: iosxr_netconf
xr_7: true
dnx: false
management_int: 0/RP0/CPU0/0
max_sid_depth: 6
asn: 65000
bgp_rrc: true
bgp_rr: false
netflow: false
xrd: true

optics:
  - {enable: false}

network_interfaces:
  - {name: GigabitEthernet0/0/0/0, descr: "ASP - CORE.101", remote_id: 101, vlan: 0, unnumbered: true, igp_inst: ASP_LAB, color: BLUE, igp_metric: 100, te_metric: 120, mtu: 8982}
  - {name: GigabitEthernet0/0/0/1, descr: "ASP - CORE.103", remote_id: 103, vlan: 0, unnumbered: true, igp_inst: ASP_LAB, color: BLUE, igp_metric: 100, te_metric: 120, mtu: 8982}
  - {name: GigabitEthernet0/0/0/2, descr: "ASP - PE.22", remote_id: 22, vlan: 0, unnumbered: true, igp_inst: ASP_LAB, color: BLUE, igp_metric: 100, te_metric: 120, mtu: 8982}  

Flex_Algo_Membership: {128, 129, 130}

Flex_Affinity:
  - {interface: Bundle-Ether1000, color: GREEN }

bfd_multipath:
  - {enable: true, location: 0/RP0/CPU0 }

bundle_members:
  - {enable: false}

breakout:
  - {enable: False}

static_routes:
  - {enable: False}

ebgp_peers:
  - { enable: true, ipv4: 10.11.21.0, remote_asn: 65100, rp4_in: pass-all, rp4_out: pass-all }
  - { enable: true, ipv4: 10.12.21.0, remote_asn: 65100, rp4_in: pass-all, rp4_out: pass-all }

ibgp_peers:
  - { enable: false }
  # - { enable: true, ipv4: 1.1.1.22 }
  # - { enable: true, ipv4: 1.1.1.23 }
  # - { enable: true, ipv4: 1.1.1.24 }

sr_pce:
  - ip: 1.1.1.51
    v6: fcbb:bb00:51::1
    precedence: 1
  - ip: 1.1.1.52
    v6: fcbb:bb00:52::1
    precedence: 2

route_reflectors:
  - ip: 1.1.1.51
    v6: fcbb:bb00:51::1
    precedence: 1
  - ip: 1.1.1.52
    v6: fcbb:bb00:52::1
    precedence: 2


sr_policy:
  manual:
    - { name: TEST_SR_POLICY, color: 100, endpoint: fcbb:bb00:23::1, locator: ASP_LAB, pce: true }
    - { name: POLICY_BLUE_PLANE, color: 105, endpoint: fcbb:bb00:23::1, locator: ASP_BLUE_Plane, pce: true }

  odn:
    # - { color: 128, metric_type: igp, pce: false, algo: 128 }
    # - { color: 129, metric_type: igp, pce: false, algo: 129 }
    # - { color: 130, metric_type: latency, pce: false, algo: 130 }

multicast:
  interfaces:
    # - {name: Bundle-Ether1000}
    # - {name: Bundle-Ether62}
    # - {name: Loopback10 }
    # - {name: Loopback0 }

igmp:
  interfaces:

services:
  l2transport_interfaces:
    - {name: GigabitEthernet0/0/0/3, descr: "EVPN VPWS P2P POLICY DC1-DC2", vlan: 103, rewrite: pop-1 }

  l3_interfaces:
    - {name: Loopback128, descr: "ASP TEST BLUE VRF INTERFACE", vlan: 0, ipv4: 10.21.128.1/32, ipv6: '2000::10:21:128:1/128'}
    - {name: Loopback129, descr: "ASP TEST RED VRF INTERFACE", vlan: 0, ipv4: 10.21.129.1/32, ipv6: '2000::10:21:129:1/128'}
    - {name: GigabitEthernet0/0/0/3, descr: "ASP - CE.11 GRT Interface", vlan: 100, ipv4: 10.11.21.1/31, ipv6: '2001::10:11:21:1/127'}
    - {name: GigabitEthernet0/0/0/3, descr: "ASP - CE.11 VRF BLUE", vlan: 101, ipv4: 10.11.21.1/31, ipv6: '2001::10:11:21:1/127'}
    - {name: GigabitEthernet0/0/0/3, descr: "ASP - CE.11 VRF RED", vlan: 102, ipv4: 10.11.21.1/31, ipv6: '2001::10:11:21:1/127'}
    - {name: GigabitEthernet0/0/0/4, descr: "ASP - CE.12 GRT Interface", vlan: 100, ipv4: 10.12.21.1/31, ipv6: '2001::10:12:21:1/127'}
    - {name: GigabitEthernet0/0/0/4, descr: "ASP - CE.12 VRF BLUE", vlan: 101, ipv4: 10.12.21.1/31, ipv6: '2001::10:12:21:1/127'}
    - {name: GigabitEthernet0/0/0/4, descr: "ASP - CE.12 VRF RED", vlan: 102, ipv4: 10.12.21.1/31, ipv6: '2001::10:12:21:1/127'}


  evpn_vpws:
    - { name: GREEN_L2VPN_LL, interface: GigabitEthernet0/0/0/3.103, evi: 103, srv6_locator: ASP_LowLatency }

  l3vpn:
    - name: BLUE
      rd: auto
      vpn_id: 128
      srv6_locator: ASP_BLUE_Plane
      interfaces: 
        - { name: Loopback128 }
        - { name: GigabitEthernet0/0/0/3.101}
        - { name: GigabitEthernet0/0/0/4.101}
      bgp_neighbors:
        - { enable: true, ipv4: 10.11.21.0, remote_asn: 65100, rp4_in: pass-all, rp4_out: pass-all }
        - { enable: true, ipv4: 10.12.21.0, remote_asn: 65100, rp4_in: pass-all, rp4_out: pass-all }

    - name: RED
      rd: auto
      vpn_id: 129
      srv6_locator: ASP_RED_Plane
      interfaces: 
        - { name: Loopback129 }
        - { name: GigabitEthernet0/0/0/3.102}
        - { name: GigabitEthernet0/0/0/4.102}
      bgp_neighbors:
        - { enable: true, ipv4: 10.11.21.0, remote_asn: 65100, rp4_in: pass-all, rp4_out: pass-all }
        - { enable: true, ipv4: 10.12.21.0, remote_asn: 65100, rp4_in: pass-all, rp4_out: pass-all }
